name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make_kparent
      run: make -C pomyang_kparent
    - name: make model
      run: make -C huer_model
    - name: make seive
      run: make -C additive_sieve
      
    - name: test
      run: pomyang_kparent/bin/test
