name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make_kparent
      run: make -C pomyang_kparent
    - name: pomyang_kparent/bin/test
      run: make
